{
 "title": "General Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gocast_temperature" }
   ]
  },
  {
   "title": "Wind speed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "gocast_wind_speed" }
   ]
  },
  {
   "title": "Pressure",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gocast_pressure" }
   ]
  },
  {
   "title": "Humidity",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "gocast_humidity" }
   ]
  },
  {
   "title": "Highest temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "targets": [
    { "expr": "max(gocast_temperature)" }
   ]
  },
  {
   "title": "Highest wind speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 16 },
   "targets": [
    { "expr": "max(gocast_wind_speed)" }
   ]
  },
  {
   "title": "Highest pressue",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 16 },
   "targets": [
    { "expr": "max(gocast_pressure)" }
   ]
  },
  {
   "title": "Highest humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 16 },
   "targets": [
    { "expr": "max(gocast_humidity)" }
   ]
  }
 ]
}