{
 "title": "Gocast Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average temperature in Berlin",
   "type": "graph",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(gocast_temperature{location=\"berlin\"})"
    }
   ]
  },
  {
   "title": "Average temperature in Berlin",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "avg(gocast_temperature{location=\"berlin\"})"
    }
   ]
  },
  {
   "title": "Average humidity in Berlin",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "avg(gocast_humidity{location=\"berlin\"})"
    }
   ]
  },
  {
   "title": "Average pressure in Berlin",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "avg(gocast_pressure{location=\"berlin\"})"
    }
   ]
  },
  {
   "title": "Average wind speed in Berlin",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "expr": "avg(gocast_wind_speed{location=\"berlin\"})"
    }
   ]
  }
 ]
}