{
 "title": "Average Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average temperature in Berlin",
   "type": "graph",
   "description": "Displays the average temperature in Berlin",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(gocast_temperature{location=\"berlin\"})",
     "legendFormat": "berlin's average temperature"
    }
   ]
  },
  {
   "title": "Highest temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    { "expr": "max(gocast_temperature)" }
   ]
  },
  {
   "title": "Average wind speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "avg(gocast_wind_speed)" }
   ]
  },
  {
   "title": "Average humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "targets": [
    { "expr": "avg(gocast_humidity)" }
   ]
  },
  {
   "title": "Average pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "targets": [
    { "expr": "avg(gocast_pressure)" }
   ]
  },
  {
   "title": "Average wind speed in Berlin",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "expr": "avg(gocast_wind_speed{location=\"berlin\"})"
    }
   ]
  },
  {
   "title": "Average humidity in Berlin",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "avg(gocast_humidity{location=\"berlin\"})"
    }
   ]
  },
  {
   "title": "Average pressure in Berlin",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "avg(gocast_pressure{location=\"berlin\"})"
    }
   ]
  }
 ]
}